### ISSUE TITLE
Addition needed | Locales at external Hosters

### ISSUE THREAD

**Issue by ichbestimmtnicht** [firefly-iii/help#8]
Please add a documentation how to install a locale at heroku (and/or other hosters?) 

Otherwise it would be neat to integrate them into the build process.

Greetings
ichbestimmtnicht

**Comment by JC5** [comment]
I believe heroku already has them integrated in the build file. But I will check. For other systems I would prefer it if users just Googled it.

**Comment by ichbestimmtnicht** [comment]
Googled it and the fix from the website with buildpacks doesn't work because you download an empty repo and just pushing `.locales` doesn't work. -> the push/build failes. Besides locale (-a) no useful command for changing is avaivable as far as I know. After your comment that my issue is fixed in the new version I deployed a new version and the german locale isn't integrated as you supposed. :)

**Comment by JC5** [comment]
You’re on Heroku, I assume? I’ll do some digging later this week. Thanks for the pointers in the right direction. 👍

**Comment by ichbestimmtnicht** [comment]
[Locale-Buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-locale)
Adding this to the build process seems easy. :) Sorry that I did not submitted the link in the first run.

**Comment by BoGnY** [comment]
I have the same problem on Heroku.. Firefly shows all number with wrong format..
I have manually added buildpack-locale to heroku buildpacks, but I don't find how to re-deploy heroku app!

**Comment by JC5** [comment]
No problem. Hopefully this weekend I can do some tinkering.

**Comment by BoGnY** [comment]
thanks
i'll make it myself but I don't find the configuration's file of heroku buildpacks (this is the first time that I use heroku)

**Comment by JC5** [comment]
I think this should be the new buildbacks section.

```
 "buildpacks": [
    {
      "url": "heroku/php"
    },
{
"url": "https://github.com/heroku/heroku-buildpack-locale"
}
  ],
```

**Comment by BoGnY** [comment]
yes, and this is how configure that buildpack:

# Configuration
Create a `.locales` file at your app's root, with all the locales you need. Example:
```
de_DE
fr_FR
```

Commit that file and trigger a new build. The specified locales will be installed by the buildpack.

**Comment by BoGnY** [comment]
@JC5 fixed, tested and pull requested 👍

**Comment by JC5** [comment]
I saw it. I consider this fixed!
